### ISSUE TITLE
Contract execution errors are not handled in gRPC api

### ISSUE THREAD

**Issue by 0mkara** [ethential/ethcode#121]
```
events.js:180      throw er; // Unhandled 'error' event      ^Error: 2 UNKNOWN: Exception iterating responses: {'message': 'execution error: revert', 'code': -32000, 'data': {'stack': 'Error: execution error: revert\n    at /app/ganache-core.docker.cli.js:69:18800\n    at /app/ganache-core.docker.cli.js:61:657175\n    at /app/ganache-core.docker.cli.js:2:62040\n    at i (/app/ganache-core.docker.cli.js:2:77139)\n    at /app/ganache-core.docker.cli.js:37:1456280\n    at /app/ganache-core.docker.cli.js:2:184425\n    at /app/ganache-core.docker.cli.js:25:392\n    at c (/app/ganache-core.docker.cli.js:25:5516)\n    at /app/ganache-core.docker.cli.js:25:317\n    at /app/ganache-core.docker.cli.js:61:675156\n    at /app/ganache-core.docker.cli.js:2:59138\n    at o (/app/ganache-core.docker.cli.js:2:62562)\n    at /app/ganache-core.docker.cli.js:2:62040\n    at /app/ganache-core.docker.cli.js:61:668716\n    at /app/ganache-core.docker.cli.js:61:666579\n    at /app/ganache-core.docker.cli.js:61:675972', 'name': 'Error'}}    at callErrorFromStatus (/home/0mkar/.vscode/extensions/quantanetwork.ethcode-0.1.8/node_modules/@grpc/grpc-js/build/src/call.js:30:26)    at Http2CallStream.<anonymous> (/home/0mkar/.vscode/extensions/quantanetwork.ethcode-0.1.8/node_modules/@grpc/grpc-js/build/src/call.js:79:34)    at Http2CallStream.emit (events.js:208:15)    at /home/0mkar/.vscode/extensions/quantanetwork.ethcode-0.1.8/node_modules/@grpc/grpc-js/build/src/call-stream.js:79:22    at processTicksAndRejections (internal/process/task_queues.js:75:11)Emitted 'error' event at:    at Http2CallStream.<anonymous> (/home/0mkar/.vscode/extensions/quantanetwork.ethcode-0.1.8/node_modules/@grpc/grpc-js/build/src/call.js:79:20)    at Http2CallStream.emit (events.js:208:15)    at /home/0mkar/.vscode/extensions/quantanetwork.ethcode-0.1.8/node_modules/@grpc/grpc-js/build/src/call-stream.js:79:22    at processTicksAndRejections (internal/process/task_queues.js:75:11) {  code: 2,  details: "Exception iterating responses: {'message': 'execution error: revert', 'code': -32000, 'data': {'stack': 'Error: execution error: revert\\n    at /app/ganache-core.docker.cli.js:69:18800\\n    at /app/ganache-core.docker.cli.js:61:657175\\n    at /app/ganache-core.docker.cli.js:2:62040\\n    at i (/app/ganache-core.docker.cli.js:2:77139)\\n    at /app/ganache-core.docker.cli.js:37:1456280\\n    at /app/ganache-core.docker.cli.js:2:184425\\n    at /app/ganache-core.docker.cli.js:25:392\\n    at c (/app/ganache-core.docker.cli.js:25:5516)\\n    at /app/ganache-core.docker.cli.js:25:317\\n    at /app/ganache-core.docker.cli.js:61:675156\\n    at /app/ganache-core.docker.cli.js:2:59138\\n    at o (/app/ganache-core.docker.cli.js:2:62562)\\n    at /app/ganache-core.docker.cli.js:2:62040\\n    at /app/ganache-core.docker.cli.js:61:668716\\n    at /app/ganache-core.docker.cli.js:61:666579\\n    at /app/ganache-core.docker.cli.js:61:675972', 'name': 'Error'}}",  metadata: Metadata {    internalRepr: Map {      'content-type' => [Array],      'content-length' => [Array],      'date' => [Array]    },    options: {}  }}
```

**Comment by Aniket6990** [comment]
after v2 merge ethcode will not use gRPC anymore.
